export const data = {
  headline: 'plansTeaser.heading',
  ctaButton: 'plansTeaser.ctaButton',
  plans: [
    {
      name: 'plansTeaser.plan1.name',
      price: 'plansTeaser.plan1.price',
      items: [
        'plansTeaser.plan1.item1',
        'plansTeaser.plan1.item2',
        'plansTeaser.plan1.item3',
        'plansTeaser.plan1.item4',
      ],
      subscribeLabel: 'plansTeaser.plan1.subscribeLabel',
      subscribeUrl: 'plansTeaser.plan1.subscribeUrl',
      remarks: 'plansTeaser.plan1.remarks',
      featured: false,
    },
    {
      name: 'plansTeaser.plan2.name',
      price: 'plansTeaser.plan2.price',
      items: [
        'plansTeaser.plan2.item1',
        'plansTeaser.plan2.item2',
        'plansTeaser.plan2.item3',
        'plansTeaser.plan2.item4',
      ],
      subscribeLabel: 'plansTeaser.plan2.subscribeLabel',
      subscribeUrl: 'plansTeaser.plan2.subscribeUrl',
      remarks: 'plansTeaser.plan2.remarks',
      featured: false,
    },
    {
      name: 'plansTeaser.plan3.name',
      price: 'plansTeaser.plan3.price',
      items: [
        'plansTeaser.plan3.item1',
        'plansTeaser.plan3.item2',
        'plansTeaser.plan3.item3',
        'plansTeaser.plan3.item4',
        'plansTeaser.plan3.item5',
      ],
      subscribeLabel: 'plansTeaser.plan3.subscribeLabel',
      subscribeUrl: 'plansTeaser.plan3.subscribeUrl',
      remarks: 'plansTeaser.plan3.remarks',
      featured: true,
    },
    {
      name: 'plansTeaser.plan4.name',
      price: 'plansTeaser.plan4.price',
      items: [
        'plansTeaser.plan4.item1',
        'plansTeaser.plan4.item2',
        'plansTeaser.plan4.item3',
        'plansTeaser.plan4.item4',
        'plansTeaser.plan4.item5',
        'plansTeaser.plan4.item6',
      ],
      subscribeLabel: 'plansTeaser.plan4.subscribeLabel',
      subscribeUrl: 'plansTeaser.plan4.subscribeUrl',
      remarks: 'plansTeaser.plan4.remarks',
      featured: false,
    },
  ],
};
